version: '3'
services: 
  frontend:
    build: Frontend/.
    ports: 
      - "8080:80"
    restart: always
    container_name: frontend
  backend:
    build: Backend/.
    ports:
      - "3000:3000"
    restart: always
    container_name: backend
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: db
    volumes: 
      - mongodata:/data/db
      
volumes:
  mongodata: